import { type VocabularyKey } from "./vocabulary";
import { type FeatureKey } from "./modules";

export type PersonaKey =
  | 'gig_worker'       // DoorDash, UberEats, Skip, Instacart
  | 'rideshare'        // Uber, Lyft, InDriver, Pathao
  | 'business_driver'  // Sales reps, realtors, consultants — MileIQ territory
  | 'contractor';      // Trades, freelance, field service

export interface PersonaConfig {
  key: PersonaKey;
  label: string;
  description: string;
  showPlatformSelectorInOnboarding: boolean;
  vocabulary: Record<VocabularyKey, string>;
  defaultFeatures: Record<FeatureKey, boolean>;
}

export const PERSONAS: Record<PersonaKey, PersonaConfig> = {
  gig_worker: {
    key: 'gig_worker',
    label: 'Gig Worker / Courier',
    description: 'Food delivery, grocery shopping, parcel courier (DoorDash, UberEats, Skip, etc.)',
    showPlatformSelectorInOnboarding: true,
    vocabulary: {
      session: 'shift',
      session_plural: 'shifts',
      platform: 'platform',
      active_miles: 'active miles',
      dead_miles: 'dead miles',
      revenue: 'earnings',
      start_cta: 'Start shift',
      end_cta: 'End shift',
      history_tab: 'Shifts',
      active_indicator: 'Active shift',
      no_sessions_yet: 'No shifts yet',
    },
    defaultFeatures: {
      session_tracking_gps: true,
      session_tracking_manual: true,
      expense_tracking: true,
      analytics_basic: true,
      vehicle_profiles: true,
      csv_export: true,
      google_drive_backup: true,
      analytics_advanced: false,
      tax_workspace: false,
      goals: false,
      schedule: false,
      gamification: false,
      pdf_reports: false,
      csv_import: false,
      android_widget: false,
      business_personal_split: false,
      mileage_log_export: false,
    },
  },
  rideshare: {
    key: 'rideshare',
    label: 'Rideshare Driver',
    description: 'Passenger transportation (Uber, Lyft, InDriver, Pathao, etc.)',
    showPlatformSelectorInOnboarding: true,
    vocabulary: {
      session: 'drive',
      session_plural: 'drives',
      platform: 'app',
      active_miles: 'fare miles',
      dead_miles: 'deadhead miles',
      revenue: 'earnings',
      start_cta: 'Go online',
      end_cta: 'Go offline',
      history_tab: 'Drives',
      active_indicator: 'Online',
      no_sessions_yet: 'No drives yet',
    },
    defaultFeatures: {
      session_tracking_gps: true,
      session_tracking_manual: true,
      expense_tracking: true,
      analytics_basic: true,
      vehicle_profiles: true,
      csv_export: true,
      google_drive_backup: true,
      analytics_advanced: true,
      tax_workspace: false,
      goals: false,
      schedule: false,
      gamification: false,
      pdf_reports: false,
      csv_import: false,
      android_widget: false,
      business_personal_split: false,
      mileage_log_export: false,
    },
  },
  business_driver: {
    key: 'business_driver',
    label: 'Business Driver / Realtor',
    description: 'Realtors, sales reps, consultants, or corporate employees tracking drives for tax write-offs',
    showPlatformSelectorInOnboarding: false,
    vocabulary: {
      session: 'drive',
      session_plural: 'drives',
      platform: 'purpose',
      active_miles: 'business miles',
      dead_miles: 'personal miles',
      revenue: 'reimbursable',
      start_cta: 'Start drive',
      end_cta: 'End drive',
      history_tab: 'Drives',
      active_indicator: 'On drive',
      no_sessions_yet: 'No drives yet',
    },
    defaultFeatures: {
      session_tracking_gps: true,
      session_tracking_manual: true,
      expense_tracking: true,
      analytics_basic: true,
      vehicle_profiles: true,
      csv_export: true,
      google_drive_backup: true,
      analytics_advanced: false,
      tax_workspace: true,
      goals: false,
      schedule: false,
      gamification: false,
      pdf_reports: false,
      csv_import: false,
      android_widget: false,
      business_personal_split: true,
      mileage_log_export: true,
    },
  },
  contractor: {
    key: 'contractor',
    label: 'Contractor / Services',
    description: 'Trades, cleaners, mobile therapists, general freelancers servicing specific clients',
    showPlatformSelectorInOnboarding: false,
    vocabulary: {
      session: 'job',
      session_plural: 'jobs',
      platform: 'client',
      active_miles: 'work miles',
      dead_miles: 'personal miles',
      revenue: 'revenue',
      start_cta: 'Start job',
      end_cta: 'End job',
      history_tab: 'Jobs',
      active_indicator: 'On job',
      no_sessions_yet: 'No jobs yet',
    },
    defaultFeatures: {
      session_tracking_gps: true,
      session_tracking_manual: true,
      expense_tracking: true,
      analytics_basic: true,
      vehicle_profiles: true,
      csv_export: true,
      google_drive_backup: true,
      analytics_advanced: false,
      tax_workspace: true,
      goals: false,
      schedule: false,
      gamification: false,
      pdf_reports: false,
      csv_import: false,
      android_widget: false,
      business_personal_split: true,
      mileage_log_export: true,
    },
  },
};
